name: Build Installers
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - mod_beta
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # os: [macos-latest, windows-latest, macos-15-intel]
        os: [ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2
      - name: Install Node.JS
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 24.9.0
      - name: Install Dependencies
        working-directory: "./MapLoader-Electron"
        run: "npm install"
      - name: Install Snapcraft and Multipass
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install snapcraft --classic --channel=7.x
          sudo snap install multipass --classic
      - name: Build Executables
        working-directory: "./MapLoader-Electron"
        run: "npm run make"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: ${{matrix.os}} Release
          path: ./MapLoader-Electron/out/make
          
          
