name: Build Installers
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    if: github.ref_type == 'tag'
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, macos-15-intel, ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2
      - name: Install Node.JS
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 24.9.0
      - name: Install Dependencies
        working-directory: "./MapLoader-Electron"
        run: "npm install"
      - name: Build Executables
        id: buildstep
        continue-on-error: true
        working-directory: "./MapLoader-Electron"
        run: "npm run make"
      - name: Upload Artifacts (Linux)
        if: ${{steps.buildstep.outcome == 'success' && matrix.os == 'ubuntu-latest'}}
        uses: actions/upload-artifact@v6.0.0
        with:
          name: ${{matrix.os}} Release
          path: ./MapLoader-Electron/out/make/zip/linux/x64/*.zip
      - name: Upload Artifacts (Windows)
        if: ${{steps.buildstep.outcome == 'success' && matrix.os == 'windows-latest'}}
        uses: actions/upload-artifact@v6.0.0
        with:
          name: ${{matrix.os}} Release
          path: ./MapLoader-Electron/out/make/squirrel.windows/x64/*.exe
      - name: Upload Artifacts (macOS)
        if: ${{steps.buildstep.outcome == 'success' && (matrix.os == 'macos-latest' || matrix.os == 'macos-15-intel')}}
        uses: actions/upload-artifact@v6.0.0
        with:
          name: ${{matrix.os}} Release
          path: ./MapLoader-Electron/out/make/*.dmg
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2
      - name: Download Artifacts
        uses: actions/download-artifact@v6.0.0
        with:
          path: ./dist
      - name: Set Release Message from tag
        run: git cat-file -p ${{github.ref_name}} | sed '1,5d' >> ./message.txt
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/macos-latest Release/*.dmg
            ./dist/macos-15-intel Release/*.dmg
            ./dist/windows-latest Release/*.exe
            ./dist/ubuntu-latest Release/*.zip
          prerelease: contains(github.ref_name, '-beta')
          body_path: ./message.txt